### Домашнее задание «Библиотека numpy. Вычислительные задачи»

#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
import numpy as np
#формируем массив от 0 до 9
array = np.arange(0, 10)
print(array)
# применяем метод flipud для реверса
res = np.flipud(array)
# вывод на печать массива от 9 до 0
res

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [19]:
a = np.random.randint(10, size = (3, 3))
a

array([[8, 2, 3],
       [7, 2, 7],
       [4, 1, 1]])

In [20]:
diag = np.diagonal(a)
diag

array([8, 2, 1])

In [31]:
sum_diag = diag.sum()
print(sum_diag)

11


In [33]:
matrix_diag = np.diag(np.arange(2, 100, 15), k=0)
matrix_diag

array([[ 2,  0,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0,  0],
       [ 0,  0, 32,  0,  0,  0,  0],
       [ 0,  0,  0, 47,  0,  0,  0],
       [ 0,  0,  0,  0, 62,  0,  0],
       [ 0,  0,  0,  0,  0, 77,  0],
       [ 0,  0,  0,  0,  0,  0, 92]])

In [34]:
diag = np.diagonal(matrix_diag)
diag

array([ 2, 17, 32, 47, 62, 77, 92])

In [35]:
sum_diag = diag.sum()
print(sum_diag)

329


#### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [30]:
A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
B = np.array([4, 12, -3])
X = np.linalg.inv(A).dot(B)

print(X)

[ 0.46666667  3.84444444 -5.55555556]


#### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”